### ISSUE TITLE
no response 

### ISSUE THREAD

**Issue by maoneid** [rofixro/vue3-realworld-app#2]
https://github.com/rofixro/vue3-realworld-app/blob/f42c3756f6cc2281d4b28691672d5a3f2cabac44/src/utils/request.ts#L22

in this code, is there any response as a return value?

**Comment by rofixro** [comment]
> https://github.com/rofixro/vue3-realworld-app/blob/f42c3756f6cc2281d4b28691672d5a3f2cabac44/src/utils/request.ts#L22
> 
> in this code, is there any response as a return value?

Yes, there is a return value in the success case. The interceptor returns data from the response object. In the error case, it doesn't return a response, but rejects a Promise with error information.
